CREATE TABLE IF NOT EXISTS students(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstname VARCHAR(25) NOT NULL,
  lastname VARCHAR(25) NOT NULL,
  cohort_id INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS cohorts(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT(25) NOT NULL
);
